### ISSUE TITLE
추천상품 SheetView

### ISSUE THREAD

**Issue by sokft** [ttakkeun/Front_iOS#38]
# 버그 리포트

## 어떤 버그인가요?

> 버그에 대해 알려주세요
추천상품 눌렀을때 SheetView가 잘리거나 여백이 너무 많이 생기는 경우가 발생
Sheet뷰 높이를 조정하는 모디피어는 고정값을 주는 경우밖에 없는데, 적절하게 높이를 설정할 수 있도록 고쳐야함.

## 어떤 상황에서 겪으셨나요?

> 버그를 겪으신 상황을 알려주세요

## 참고할만한 자료가 있을까요?

> 참고자료가 있다면 첨부해주세요

**Comment by JEONG-J** [comment]
요것은 내가 나중에 상품 뷰 다 만들고 연결 시킬 때 해결할게
