### ISSUE TITLE
8.1 프로필 생성뷰 

### ISSUE THREAD

**Issue by alice0047** [ttakkeun/Front_iOS#63]
## Issue: ✅ Todo
Todo 사항을 입력해주세요

생년월일 피커
버튼 눌렀을 때 연두색 테두리 
해당 값 입력되면 체크 표시

+ API 연동 가능하다면 

## ✏️ Description
설명을 작성합니다

위 TODO와 같음 

## To-Do List
- [ ] 할일 1 버튼 눌렀을 때 연두색 테두리, 값 입력되면 체크 표시
- [ ] 할일 2 생년 월일 피커

**Comment by JEONG-J** [comment]
@alice0047 그래서 두 개의 할일에 대해 다 됐는가?
